language: node_js
node_js:
  - "10"

install:
  - yarn

script:
  - yarn build

after_success:
  - cd ./dist
  - git init
  # - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - git add .
  - git commit -m "update from travis-ci"
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:dist
  - git push --quiet --force "https://${CODING_TOKEN}@${CODING_REF}" master:dist

branches:
  only:
    - main
